module.exports = {
    oblastiOption: {
        reply_markup: JSON.stringify({
            inline_keyboard: [
                [{ text: 'Черкаська', callback_data: 'cherkaska' }, { text: 'Чернігівська', callback_data: 'chernihivska' }, { text: 'Чернівецька', callback_data: 'chernivecka' }],
                [{ text: 'Дніпропетрівська', callback_data: 'dnipropetrovska' }, { text: 'Донецька', callback_data: 'donetska' }, { text: 'Франківська', callback_data: 'frankivska' }],
                [{ text: 'Харківська', callback_data: 'kharkivska' }, { text: 'Херсонська', callback_data: 'khersonska' }, { text: 'Хмельницька', callback_data: 'khmelnitska' }],
                [{ text: 'Київська', callback_data: 'kiivska' }, { text: 'Кіровоградська', callback_data: 'kirovogradska' }, { text: 'Луганська', callback_data: 'luganskaya' }],
                [{ text: 'Львівська', callback_data: 'lvivska' }, { text: 'Миколаївська', callback_data: 'mykolaivskaya' }, { text: 'Одеська', callback_data: 'odeska' }],
                [{ text: 'Полтавська', callback_data: 'poltavska' }, { text: 'Рівненська', callback_data: 'rivnenska' }, { text: 'Сумська', callback_data: 'symska' }],
                [{ text: 'Тернопільська', callback_data: 'ternopilska' }, { text: 'Вінницька', callback_data: 'vinnitska' }, { text: 'Волинська', callback_data: 'volunska' }],
                [{ text: 'Закарпатська', callback_data: 'zakarpatska' }, { text: 'Запорізька', callback_data: 'zaporizka' }, { text: 'Житомирська', callback_data: 'zhytomirska' }],
            ]
        })
    },
    specialPlaces: {
        reply_markup: JSON.stringify({
            inline_keyboard: [
                [{ text: 'Хотянівка', callback_data: 'khotianivka' }, { text: 'Бобриця', callback_data: 'bobritsa' }],
            ]
        })
    },
    skyNow: {
        cherkaska: `https://www.meteoprog.ua/ua/weather/Chercasy`,
        chernihivska: `https://www.meteoprog.ua/ua/weather/Chernigiv`,
        chernivecka: `https://www.meteoprog.ua/ua/weather/Chernivtsi`,
        dnipropetrovska: `https://www.meteoprog.ua/ua/weather/Dnipropetrovsk`,
        donetska: `https://www.meteoprog.ua/ua/weather/Donetsk`,
        frankivska: `https://www.meteoprog.ua/ua/weather/Ivanofrankivsk`,
        kharkivska: `https://www.meteoprog.ua/ua/weather/Kharkiv`,
        khersonska: `https://www.meteoprog.ua/ua/weather/Kherson`,
        khmelnitska: `https://www.meteoprog.ua/ua/weather/Khmelnytskyi`,
        kiivska: `https://www.meteoprog.ua/ua/weather/Kyiv`,
        kirovogradska: `https://www.meteoprog.ua/ua/weather/Kirovohrad`,
        luganskaya: `https://www.meteoprog.ua/ua/weather/Luhansk`,
        lvivska: `https://www.meteoprog.ua/ua/weather/Lviv`,
        mykolaivskaya: `https://www.meteoprog.ua/ua/weather/Mikolaiv`,
        odeska: `https://www.meteoprog.ua/ua/weather/Odesa`,
        poltavska: `https://www.meteoprog.ua/ua/weather/Poltava`,
        rivnenska: `https://www.meteoprog.ua/ua/weather/Rivne`,
        symska: `https://www.meteoprog.ua/ua/weather/Sumy`,
        ternopilska: `https://www.meteoprog.ua/ua/weather/Ternopil`,
        vinnitska: `https://www.meteoprog.ua/ua/weather/Vinnitsa`,
        volunska: `https://www.meteoprog.ua/ua/weather/Lutsk`,
        zakarpatska: `https://www.meteoprog.ua/ua/weather/Uzhgorod`,
        zaporizka: `https://www.meteoprog.ua/ua/weather/Zaporizhzhia`,
        zhytomirska: `https://www.meteoprog.ua/ua/weather/Zhytomyr`,
        khotianivka: `https://www.meteoprog.ua/ua/weather/Khotyanivka-kyivska/`,
        bobritsa: `https://www.meteoprog.ua/ua/weather/Bobrytsya-kyivska/`,
    },
    wickliPressure: {
        cherkaska: `https://www.meteoprog.ua/ua/weather/Chercasy/6_10/`,
        chernihivska: `https://www.meteoprog.ua/ua/weather/Chernigiv/6_10/`,
        chernivecka: `https://www.meteoprog.ua/ua/weather/Chernivtsi/6_10/`,
        dnipropetrovska: `https://www.meteoprog.ua/ua/weather/Dnipropetrovsk/6_10/`,
        donetska: `https://www.meteoprog.ua/ua/weather/Donetsk/6_10/`,
        frankivska: `https://www.meteoprog.ua/ua/weather/Ivanofrankivsk/6_10/`,
        kharkivska: `https://www.meteoprog.ua/ua/weather/Kharkiv/6_10/`,
        khersonska: `https://www.meteoprog.ua/ua/weather/Kherson/6_10/`,
        khmelnitska: `https://www.meteoprog.ua/ua/weather/Khmelnytskyi/6_10/`,
        kiivska: `https://www.meteoprog.ua/ua/weather/Kyiv/6_10/`,
        kirovogradska: `https://www.meteoprog.ua/ua/weather/Kirovohrad/6_10/`,
        luganskaya: `https://www.meteoprog.ua/ua/weather/Luhansk/6_10/`,
        lvivska: `https://www.meteoprog.ua/ua/weather/Lviv/6_10/`,
        mykolaivskaya: `https://www.meteoprog.ua/ua/weather/Mikolaiv/6_10/`,
        odeska: `https://www.meteoprog.ua/ua/weather/Odesa/6_10/`,
        poltavska: `https://www.meteoprog.ua/ua/weather/Poltava/6_10/`,
        rivnenska: `https://www.meteoprog.ua/ua/weather/Rivne/6_10/`,
        symska: `https://www.meteoprog.ua/ua/weather/Sumy/6_10/`,
        ternopilska: `https://www.meteoprog.ua/ua/weather/Ternopil/6_10/`,
        vinnitska: `https://www.meteoprog.ua/ua/weather/Vinnitsa/6_10/`,
        volunska: `https://www.meteoprog.ua/ua/weather/Lutsk/6_10/`,
        zakarpatska: `https://www.meteoprog.ua/ua/weather/Uzhgorod/6_10/`,
        zaporizka: `https://www.meteoprog.ua/ua/weather/Zaporizhzhia/6_10/`,
        zhytomirska: `https://www.meteoprog.ua/ua/weather/Zhytomyr/6_10/`,
        khotianivka: `https://www.meteoprog.ua/ua/weather/Khotyanivka-kyivska/6_10/`,
        bobritsa: `https://www.meteoprog.ua/ua/weather/Bobrytsya-kyivska/6_10/`,
    },
    images: {
        cherkaska: './media/cities/cherkaska.jpg',
        chernihivska: './media/cities/chernihivska.jpg',
        chernivecka: './media/cities/chernivecka.jpg',
        dnipropetrovska: './media/cities/dnipropetrovska.jpg',
        donetska: './media/cities/donetska.jpg',
        frankivska: './media/cities/frankivska.jpg',
        kharkivska: './media/cities/kharkivska.jpg',
        khersonska: './media/cities/khersonska.jpg',
        khmelnitska: './media/cities/khmelnitska.jpeg',
        kiivska: './media/cities/kyiv.jpg',
        kirovogradska: './media/cities/kirovogradska.jpg',
        luganskaya: './media/cities/luganskaya.jpg',
        lvivska: './media/cities/lvivska.jpg',
        mykolaivskaya: './media/cities/mykolaivskaya.jpg',
        odeska: './media/cities/odeska.jpg',
        poltavska: './media/cities/poltavska.jpg',
        rivnenska: './media/cities/rivnenska.jpg',
        symska: './media/cities/symska.jpg',
        ternopilska: './media/cities/ternopilska.jpg',
        vinnitska: './media/cities/vinnitska.jpeg',
        volunska: './media/cities/volunska.jpg',
        zakarpatska: './media/cities/zakarpatska.jpg',
        zaporizka: './media/cities/zaporizka.jpg',
        zhytomirska: './media/cities/zhytomirska.jpeg',
        khotianivka: './media/cities/khotianivka.jpg',
        bobritsa: './media/cities/khotianivka.jpg',
    },
    watherTemp: {
        cherkaska: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-cherkasy-sea-temperature`,
        chernihivska: `https://ukr.seatemperature.net/zaraz/ukraine/desna-river-near-chernigov-sea-temperature`,
        chernivecka: `https://ukr.seatemperature.net/zaraz/ukraine/novodnestrovsk-ukraine-sea-temperature`,
        dnipropetrovska: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-dnepropetrovsk-sea-temperature`,
        donetska: `https://ukr.seatemperature.net/zaraz/ukraine/donetsk-ukraine-sea-temperature`,
        frankivska: `https://ukr.seatemperature.net/zaraz/ukraine/mukachevo-ukraine-sea-temperature`,
        kharkivska: `https://ukr.seatemperature.net/zaraz/ukraine/pechenezhskoe-vodohranilichshe-ukraine-sea-temperature`,
        khersonska: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-kherson-sea-temperature`,
        khmelnitska: `https://ukr.seatemperature.net/zaraz/ukraine/hmelnitskiiy-ukraine-sea-temperature`,
        kiivska: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-kiev-sea-temperature`,
        kirovogradska: `https://ukr.seatemperature.net/zaraz/ukraine/kropivnitskiiy-ukraine-sea-temperature`,
        luganskaya: `https://ukr.seatemperature.net/zaraz/ukraine/donetsk-ukraine-sea-temperature`,
        lvivska: `https://ukr.seatemperature.net/zaraz/ukraine/dnestrovskiiy-kanon-ukraine-sea-temperature`,
        mykolaivskaya: `https://ukr.seatemperature.net/zaraz/ukraine/nikolaev-ukraine-sea-temperature`,
        odeska: `https://ukr.seatemperature.net/zaraz/ukraine/odessa-odeska-oblast-ukraine-sea-temperature`,
        poltavska: `https://ukr.seatemperature.net/zaraz/ukraine/poltava-ukraine-sea-temperature`,
        rivnenska: `https://ukr.seatemperature.net/zaraz/ukraine/hmelnitskiiy-ukraine-sea-temperature`,
        symska: `https://ukr.seatemperature.net/zaraz/ukraine/sumy-ukraine-sea-temperature`,
        ternopilska: `https://ukr.seatemperature.net/zaraz/ukraine/dnestrovskiiy-kanon-ukraine-sea-temperature`,
        vinnitska: `https://ukr.seatemperature.net/zaraz/ukraine/vinnitsa-ukraine-sea-temperature`,
        volunska: `https://ukr.seatemperature.net/zaraz/ukraine/lake-svitiaz-sea-temperature`,
        zakarpatska: `https://ukr.seatemperature.net/zaraz/ukraine/uzhgorod-ukraine-sea-temperature`,
        zaporizka: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-zaporozhye-sea-temperature`,
        zhytomirska: `https://ukr.seatemperature.net/zaraz/ukraine/teterev-river-near-zhitomir-sea-temperature`,
        khotianivka: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-kiev-sea-temperature`,
        bobritsa: `https://ukr.seatemperature.net/zaraz/ukraine/dnipro-river-near-kiev-sea-temperature`,
    }
}